### ISSUE TITLE
Github is deprecating node.js 12. This action should be updated to node.js 16

### ISSUE THREAD

**Issue by okibcn** [andymckay/cancel-action#8]
When the action is used, Github provides this warning:

Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: andymckay/cancel-action@0.2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by andymckay** [comment]
This was updated here https://github.com/andymckay/cancel-action/commit/7b96a32dd081a9dfc4c184e0c89501ebb2e33439, so if you use the latest version you should be good.
